<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-30T19:00:28 IST" name="Default suite" finished-at="2025-05-30T19:00:39 IST" duration-ms="11249">
    <groups>
    </groups>
    <test started-at="2025-05-30T19:00:28 IST" name="Default test" finished-at="2025-05-30T19:00:39 IST" duration-ms="11249">
      <class name="com.bookcart.tests.CheckoutTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.bookcart.tests.CheckoutTest@55141def]" started-at="2025-05-30T19:00:28 IST" name="setUp" finished-at="2025-05-30T19:00:29 IST" duration-ms="1471" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="searchProduct()[pri:0, instance:com.bookcart.tests.CheckoutTest@55141def]" started-at="2025-05-30T19:00:29 IST" name="searchProduct" finished-at="2025-05-30T19:00:30 IST" duration-ms="557" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchProduct -->
        <test-method signature="addToCartAndGoToCart()[pri:0, instance:com.bookcart.tests.CheckoutTest@55141def]" started-at="2025-05-30T19:00:30 IST" name="addToCartAndGoToCart" finished-at="2025-05-30T19:00:34 IST" depends-on-methods="com.bookcart.tests.CheckoutTest.searchProduct" duration-ms="4103" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Cart Page title check expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Cart Page title check expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at com.bookcart.tests.CheckoutTest.addToCartAndGoToCart(CheckoutTest.java:33)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addToCartAndGoToCart -->
        <test-method signature="proceedToCheckout()[pri:0, instance:com.bookcart.tests.CheckoutTest@55141def]" started-at="2025-05-30T19:00:34 IST" name="proceedToCheckout" finished-at="2025-05-30T19:00:34 IST" depends-on-methods="com.bookcart.tests.CheckoutTest.addToCartAndGoToCart" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.bookcart.tests.CheckoutTest.proceedToCheckout() on instance com.bookcart.tests.CheckoutTest@55141def depends on not successfully finished methods 
[com.bookcart.tests.CheckoutTest.addToCartAndGoToCart() on instance com.bookcart.tests.CheckoutTest@55141def]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.bookcart.tests.CheckoutTest.proceedToCheckout() on instance com.bookcart.tests.CheckoutTest@55141def depends on not successfully finished methods 
[com.bookcart.tests.CheckoutTest.addToCartAndGoToCart() on instance com.bookcart.tests.CheckoutTest@55141def]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:157)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- proceedToCheckout -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.bookcart.tests.CheckoutTest@55141def]" started-at="2025-05-30T19:00:34 IST" name="tearDown" finished-at="2025-05-30T19:00:39 IST" duration-ms="5102" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.bookcart.tests.CheckoutTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
